### ISSUE TITLE
Clover KextToPatch

### ISSUE THREAD

**Issue by qwqVictor** [thicongtu2/AppleHDA#7]
Would you mind giving a solution for Clover KextToPatch to keep the integrity of the system original kexts?

**Comment by nguyenngocanh94** [comment]
yeah, try it AppleHDA-on the fly.
here is a tutorial https://www.tonymacx86.com/threads/patch-applehda-kext-on-the-fly-with-clover-bootloader.118877/

**Comment by qwqVictor** [comment]
Thank you very much. I'm going to do some work for it. Then if I succeed, I'll share my experiences and close this issue.
